### ISSUE TITLE
Create packagist 

### ISSUE THREAD

**Issue by oleg-andreyev** [dbalabka/php-enumeration#5]
https://packagist.org/?query=dbalabka%2Fphp-enumeration

**Comment by dbalabka** [comment]
There is only one package with same name https://packagist.org/packages/freshp/php-enumeration
There are two ways:
1. Leave as is
2. Rename package to `php-enumeration-class` for example

**Comment by oleg-andreyev** [comment]
I would leave as is.

**Comment by dbalabka** [comment]
Package registered on Packagist 🙌🎉
https://packagist.org/packages/dbalabka/php-enumeration
